In [4]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8327, 1583, 7453, 8836], [8327, 1583, 7453, 1235], [8327, 5907, 7453, 9498], [9784, 4598, 2399, 8925, 7184], [9784, 4598, 2399, 8925, 1370], [9303, 8327, 4967, 7453, 2614], [5890, 9182, 8721, 8925]]


#### Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8327 1583 7453 8836]
 [   0    0    0    0 8327 1583 7453 1235]
 [   0    0    0    0 8327 5907 7453 9498]
 [   0    0    0 9784 4598 2399 8925 7184]
 [   0    0    0 9784 4598 2399 8925 1370]
 [   0    0    0 9303 8327 4967 7453 2614]
 [   0    0    0    0 5890 9182 8721 8925]]


In [13]:
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[[ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871
    0.01967317 -0.02309778 -0.01341135 -0.03348305  0.01977421]
  [ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871
    0.01967317 -0.02309778 -0.01341135 -0.03348305  0.01977421]
  [ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871
    0.01967317 -0.02309778 -0.01341135 -0.03348305  0.01977421]
  [ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871
    0.01967317 -0.02309778 -0.01341135 -0.03348305  0.01977421]
  [-0.00438813 -0.02832878  0.04825579  0.0030873  -0.04798076
    0.0307153  -0.01684147 -0.03966387 -0.00239149 -0.00705819]
  [ 0.04202818 -0.02206673  0.02512233 -0.01515821 -0.03094423
   -0.02721139 -0.04045576  0.00164524 -0.03250699 -0.01356842]
  [ 0.03892704  0.0308674  -0.01448743 -0.0366542   0.00708435
   -0.02282792 -0.01965376 -0.02766958 -0.01727515  0.02707399]
  [ 0.02709713  0.01773885 -0.04054911  0.04922578  0.03741078
   -0.0109

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 8327, 1583, 7453, 8836])

In [18]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[[ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871  0.01967317
  -0.02309778 -0.01341135 -0.03348305  0.01977421]
 [ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871  0.01967317
  -0.02309778 -0.01341135 -0.03348305  0.01977421]
 [ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871  0.01967317
  -0.02309778 -0.01341135 -0.03348305  0.01977421]
 [ 0.01035106  0.04151366 -0.02659745 -0.03621652 -0.03387871  0.01967317
  -0.02309778 -0.01341135 -0.03348305  0.01977421]
 [-0.00438813 -0.02832878  0.04825579  0.0030873  -0.04798076  0.0307153
  -0.01684147 -0.03966387 -0.00239149 -0.00705819]
 [ 0.04202818 -0.02206673  0.02512233 -0.01515821 -0.03094423 -0.02721139
  -0.04045576  0.00164524 -0.03250699 -0.01356842]
 [ 0.03892704  0.0308674  -0.01448743 -0.0366542   0.00708435 -0.02282792
  -0.01965376 -0.02766958 -0.01727515  0.02707399]
 [ 0.02709713  0.01773885 -0.04054911  0.04922578  0.03741078 -0.01093734
  -0.00213113 